name: apk_parser
description: >
  A pure dart library for parsing android apk data
version: 0.0.1+1
author: Andres Araujo <a.araujo.azua@gmail.com>
homepage: https://github.com/andresaraujo/apk_parser.dart
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  archive: ">=1.0.19 <2.0.0"
  xmlstream: ">=0.10.0 <0.11.0"
dev_dependencies:
  unittest: any
